In [2]:
import pandas as pd
import numpy as np

data = {
    'patient_id': [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,101,107,118,119,120],
    'age': ['25','34',None,'45','29',None,'38','52','27','41',
            '33','unknown','48','26','35','25','38','31',None,'44'],
    'weight': ['70','65','80',None,'75',None,'68','90','72','85',
               '78',None,'82','69','N/A','70','68','74',None,'88'],
    'blood_pressure': [120,130,None,140,125,None,135,None,118,145,
                      128,None,138,122,None,120,135,126,None,142],
    'medication': ['Aspirin','Metformin','Lisinopril',None,'Aspirin',
                   'Metformin','Lisinopril','Aspirin',None,'Metformin',
                   'Lisinopril','Aspirin',None,'Metformin','Aspirin',
                   'Aspirin','Lisinopril','Metformin','Aspirin',None],
    'insurance_provider': ['Blue Cross','Aetna','Cigna','UnitedHealth',None,
                          'Blue Cross','Aetna','Cigna','UnitedHealth','Blue Cross',
                          'Aetna',None,'UnitedHealth','Blue Cross','Aetna',
                          'Blue Cross','Aetna','Cigna','UnitedHealth',None]
}

df = pd.DataFrame(data)

    patient_id      age weight  blood_pressure  medication insurance_provider
0          101       25     70           120.0     Aspirin         Blue Cross
1          102       34     65           130.0   Metformin              Aetna
2          103     None     80             NaN  Lisinopril              Cigna
3          104       45   None           140.0        None       UnitedHealth
4          105       29     75           125.0     Aspirin               None
5          106     None   None             NaN   Metformin         Blue Cross
6          107       38     68           135.0  Lisinopril              Aetna
7          108       52     90             NaN     Aspirin              Cigna
8          109       27     72           118.0        None       UnitedHealth
9          110       41     85           145.0   Metformin         Blue Cross
10         111       33     78           128.0  Lisinopril              Aetna
11         112  unknown   None             NaN     Aspirin               None
12         113       48     82           138.0        None       UnitedHealth
13         114       26     69           122.0   Metformin         Blue Cross
14         115       35    N/A             NaN     Aspirin              Aetna
15         101       25     70           120.0     Aspirin         Blue Cross
16         107       38     68           135.0  Lisinopril              Aetna
17         118       31     74           126.0   Metformin              Cigna
18         119     None   None             NaN     Aspirin       UnitedHealth
19         120       44     88           142.0        None               None

In [4]:
#Task 1 — Inspect the Data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 17 non-null     object
 2   weight              16 non-null     object
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object
 5   insurance_provider  17 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ KB

In [5]:
df.isnull().sum()

patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

In [6]:
(df.isnull().sum() / len(df)) * 100

patient_id             0.0
age                   15.0
weight                20.0
blood_pressure        30.0
medication            20.0
insurance_provider    15.0
dtype: float64

In [8]:
df.duplicated().sum()

np.int64(2)

In [15]:
#Task 2 — Data Type Conversion
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['weight'] = pd.to_numeric(df['weight'], errors='coerce')
df[['age','weight']].isnull().sum()
df['insurance_provider'] = df['insurance_provider'].astype('category')
df.dtypes

patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object

In [19]:
#Task 3: Handle Missing Values
df['age'].fillna(df['age'].median(), inplace=True)
df['weight'].fillna(df['weight'].median(), inplace=True)
df['blood_pressure'].fillna(df['blood_pressure'].median(), inplace=True)

/tmp/ipykernel_319/85799672.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)
/tmp/ipykernel_319/85799672.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['weight'].fillna(df['weight'].median(), inplace=True)
/tmp/ipykernel_319/85799672.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['blood_pressure'].fillna(df['blood_pressure'].median(), inplace=True)

In [20]:
df['medication'].fillna(df['medication'].mode()[0], inplace=True)

/tmp/ipykernel_319/409894974.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['medication'].fillna(df['medication'].mode()[0], inplace=True)

In [21]:
df['insurance_provider'].fillna('Unknown', inplace=True)

/tmp/ipykernel_319/3182426868.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['insurance_provider'].fillna('Unknown', inplace=True)

TypeError: Cannot setitem on a Categorical with a new category (Unknown), set the categories first

In [22]:
df.isnull().sum()

patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    3
dtype: int64

In [23]:
#Task 4 — Handle Duplicates
df[df.duplicated(keep=False)]

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna

In [24]:
df[df.duplicated(subset=['patient_id'])]

    patient_id   age  weight  blood_pressure  medication insurance_provider
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna

In [25]:
print("Before:", df.shape)

Before: (20, 6)

In [26]:
df = df.drop_duplicates(subset=['patient_id'], keep='first')

In [27]:
print("After:", df.shape)

After: (18, 6)

In [28]:
#Task 5 — Complete Workflow with Verification
df_clean = df.copy()

In [29]:
print("Shape before:", df_clean.shape)
print("Missing before:\n", df_clean.isnull().sum())
print("Duplicates before:", df_clean.duplicated(subset=['patient_id']).sum())
print("Dtypes before:\n", df_clean.dtypes)

Shape before: (18, 6)
Missing before:
 patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    3
dtype: int64
Duplicates before: 0
Dtypes before:
 patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object

In [33]:
df_clean['age'] = pd.to_numeric(df_clean['age'], errors='coerce')
df_clean['weight'] = pd.to_numeric(df_clean['weight'], errors='coerce')
df_clean['insurance_provider'] = df_clean['insurance_provider'].astype('category')

In [35]:
df_clean['age'].fillna(df_clean['age'].median(), inplace=True)
df_clean['weight'].fillna(df_clean['weight'].median(), inplace=True)
df_clean['blood_pressure'].fillna(df_clean['blood_pressure'].median(), inplace=True)
df_clean['medication'].fillna(df_clean['medication'].mode()[0], inplace=True)
df_clean['insurance_provider'].fillna('Unknown', inplace=True)

/tmp/ipykernel_319/3735712386.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['age'].fillna(df_clean['age'].median(), inplace=True)
/tmp/ipykernel_319/3735712386.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['weight'].fillna(df_clean['weight'].median(), inplace=True)
/tmp/ipykernel_319/3735712386.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['blood_pressure'].fillna(df_clean['blood_pressure'].median(), inplace=True)
/tmp/ipykernel_319/3735712386.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['medication'].fillna(df_clean['medication'].mode()[0], inplace=True)

TypeError: Cannot setitem on a Categorical with a new category (Unknown), set the categories first

In [36]:
df_clean = df_clean.drop_duplicates(subset=['patient_id'], keep='first')

In [37]:
print("\n----- VERIFICATION REPORT -----")

print("Shape after:", df_clean.shape)

print("\nMissing values after:")
print(df_clean.isnull().sum())

print("\nDuplicates after:")
print(df_clean.duplicated(subset=['patient_id']).sum())

print("\nData types after:")
print(df_clean.dtypes)

----- VERIFICATION REPORT -----
Shape after: (18, 6)

Missing values after:
patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    3
dtype: int64

Duplicates after:
0

Data types after:
patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object